#!/bin/bash
# Startup script for the nginx Web Server
# chkconfig: - 85 15
# description: nginx is a World Wide Web server. It is used to serve
# processname: nginx
nginxd=/usr/local/nginx/sbin/nginx
nginx_config=/usr/local/nginx/conf/nginx.conf
nginx_pid=/usr/local/nginx/logs/nginx.pid
 
REIVAL=0
prog="nginx"
 
. /etc/rc.d/init.d/functions
 
. /etc/sysconfig/network
 
[ ${NETWORKING} = "no" ] && exit 0
[ -x $nginxd ] || exit 0
 
start() {
if [ -e $nginx_pid ];then
    echo "nginx already running..."
    exit 1
fi
    echo -n $"starting $prog: "
    daemon $nginxd -c ${nginx_config}
    RETVAL=$?
    echo
    [ $RETVAL = 0 ] && touch /usr/local/nginx/logs/nginx
    return $RETVAL
}
 
stop() {
    echo -n $"stoping $prog: "
    killproc $nginxd
    RETVAL=$?
    echo
    [ $RETVAL = 0 ] && rm -f /usr/local/nginx/logs/nginx /usr/local/nginx/logs/nginx.pid
}
reload() {
    echo -n $"reloading $prog: "
    $nginxd -s reload
    RETVAL=$?
    echo
}
case "$1" in
start)
    start
    ;;
stop)
    stop
    ;;
reload)
    reload
    ;;
restart)
    stop
    start
    ;;
status)
    status $prog
    RETVAL=$?
    ;;
*)
    echo $"Usage: $prog {start|stop|restart|reload|status}"
    exit 1
esac
exit $RETVAL